services:
  web:
    image: beloyal/athena:latest
    ports:
      - "8000:8000"
    environment:
      ONEPASS_CONNECT_TOKEN: ${ONEPASS_CONNECT_TOKEN}
      ONEPASS_CONNECT_HOST: ${ONEPASS_CONNECT_HOST}
      LOGGING_LEVEL: "WARNING"
      GLOBAL_APP_ENV: "local"
      FRONTEND_URL: ${FRONTEND_URL}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      -  "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: