services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      OP_SERVICE_ACCOUNT_TOKEN: ${OP_SERVICE_ACCOUNT_TOKEN}
      LOGGING_LEVEL: "WARNING"
      GLOBAL_APP_ENV: "local"
      FRONTEND_URL: ${FRONTEND_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      -  "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: