"""Init database

Revision ID: 80d895ed90d8
Revises: 
Create Date: 2025-07-07 15:21:57.350989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '80d895ed90d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_sessions',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('session_string', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('owner_id', 'session_string'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('telegram_entities',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('small_pfp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('unread_count', sa.Integer(), nullable=False),
    sa.Column('last_message_date', sa.DateTime(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('members_count', sa.Integer(), nullable=False),
    sa.Column('is_creator', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['login_sessions.owner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'chat_id')
    )
    op.create_table('chat_messages',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id', 'chat_id'], ['telegram_entities.owner_id', 'telegram_entities.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'chat_id', 'message_id')
    )
    op.create_table('chat_summaries',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_date', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id', 'chat_id'], ['telegram_entities.owner_id', 'telegram_entities.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'chat_id', 'summary_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_summaries')
    op.drop_table('chat_messages')
    op.drop_table('telegram_entities')
    op.drop_table('login_sessions')
    # ### end Alembic commands ###
