"""pyrogram postgres

Revision ID: b4191054611a
Revises: f9e36d62f551
Create Date: 2025-07-09 01:58:01.625042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4191054611a'
down_revision: Union[str, Sequence[str], None] = 'f9e36d62f551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_sessions',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('dc_id', sa.BigInteger(), nullable=False),
    sa.Column('api_id', sa.BigInteger(), nullable=False),
    sa.Column('test_mode', sa.Boolean(), nullable=False),
    sa.Column('auth_key', sa.LargeBinary(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('owner_id', 'dc_id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('telegram_version',
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('number')
    )
    op.create_table('telegram_peers',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('access_hash', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('last_update_on', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['telegram_sessions.owner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_index(op.f('ix_telegram_peers_id'), 'telegram_peers', ['id'], unique=True)
    op.create_index(op.f('ix_telegram_peers_phone_number'), 'telegram_peers', ['phone_number'], unique=False)
    op.create_table('telegram_update_state',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('pts', sa.BigInteger(), nullable=False),
    sa.Column('qts', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['telegram_sessions.owner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'id')
    )
    op.create_table('telegram_usernames',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['telegram_peers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['telegram_sessions.owner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', 'id')
    )
    op.create_index(op.f('ix_telegram_usernames_id'), 'telegram_usernames', ['id'], unique=False)
    op.create_index(op.f('ix_telegram_usernames_username'), 'telegram_usernames', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_usernames_username'), table_name='telegram_usernames')
    op.drop_index(op.f('ix_telegram_usernames_id'), table_name='telegram_usernames')
    op.drop_table('telegram_usernames')
    op.drop_table('telegram_update_state')
    op.drop_index(op.f('ix_telegram_peers_phone_number'), table_name='telegram_peers')
    op.drop_index(op.f('ix_telegram_peers_id'), table_name='telegram_peers')
    op.drop_table('telegram_peers')
    op.drop_table('telegram_version')
    op.drop_table('telegram_sessions')
    # ### end Alembic commands ###
