"""Initial migration with login and summary schemas

Revision ID: eb575135994c
Revises: 
Create Date: 2025-07-07 10:52:49.856374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb575135994c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_sessions',
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('session_string', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_onboarded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('owner_id', 'session_string')
    )
    op.drop_constraint(op.f('chat_messages_owner_id_chat_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'telegram_entities', ['owner_id', 'chat_id'], ['owner_id', 'chat_id'], ondelete='CASCADE')
    op.drop_column('chat_messages', 'has_link')
    op.drop_column('chat_messages', 'link_preview_description')
    op.drop_column('chat_messages', 'link_preview_title')
    op.drop_column('chat_messages', 'is_self')
    op.drop_column('chat_messages', 'reaction_count')
    op.drop_column('chat_messages', 'is_contact')
    op.drop_column('chat_messages', 'has_mention')
    op.drop_column('chat_messages', 'is_premium')
    op.drop_column('chat_messages', 'media_score')
    op.drop_column('chat_messages', 'is_bot')
    op.drop_constraint(op.f('chat_summaries_owner_id_chat_id_fkey'), 'chat_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'chat_summaries', 'telegram_entities', ['owner_id', 'chat_id'], ['owner_id', 'chat_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'telegram_entities', 'login_sessions', ['owner_id'], ['owner_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_entities', type_='foreignkey')
    op.drop_constraint(None, 'chat_summaries', type_='foreignkey')
    op.create_foreign_key(op.f('chat_summaries_owner_id_chat_id_fkey'), 'chat_summaries', 'telegram_entities', ['owner_id', 'chat_id'], ['owner_id', 'chat_id'])
    op.add_column('chat_messages', sa.Column('is_bot', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('media_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('has_mention', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('is_contact', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('reaction_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('is_self', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('link_preview_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('link_preview_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('has_link', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_owner_id_chat_id_fkey'), 'chat_messages', 'telegram_entities', ['owner_id', 'chat_id'], ['owner_id', 'chat_id'])
    op.drop_table('login_sessions')
    # ### end Alembic commands ###
