"""Summary processing

Revision ID: f9e36d62f551
Revises: 80d895ed90d8
Create Date: 2025-07-08 19:13:56.947612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9e36d62f551'
down_revision: Union[str, Sequence[str], None] = '80d895ed90d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_summaries', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('chat_summaries', sa.Column('is_processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_summaries', 'is_processed')
    op.drop_column('chat_summaries', 'is_read')
    # ### end Alembic commands ###
