from enum import Enum

"""
EVENT BUS TOPICS CONSTANTS
"""

FETCH_PREFIX = "fetch"
CREATE_PREFIX = "create"
UPDATE_PREFIX = "update"
DELETE_PREFIX = "delete"
QUERY_PREFIX = "query"
EXISTS_PREFIX = "exists"
AGENT_PREFIX = "agent"
CRUD_OPERATIONS = (
    ("CREATE", CREATE_PREFIX),
    ("FETCH", FETCH_PREFIX),
    ("UPDATE", UPDATE_PREFIX),
    ("DELETE", DELETE_PREFIX),
)


"""
TELEGRAM EVENTS
"""
TELEGRAM_PREFIX = "telegram"
CHANNELS_PREFIX = f"{TELEGRAM_PREFIX}.channels"
MESSAGES_PREFIX = f"{TELEGRAM_PREFIX}.messages"


class MessageTopics(Enum):
    RESPOND_TO_MESSAGE = f"{MESSAGES_PREFIX}.respond"


"""
TELEMETREE INTEGRATION EVENTS
"""

TELEMETREE_PREFIX = "telemetree"
TELEMETREE_CHANNELS_PREFIX = f"{TELEMETREE_PREFIX}.channels"


class TelemetreeTopics(Enum):
    GET_CHANNEL_POSTS = f"{TELEMETREE_CHANNELS_PREFIX}.{FETCH_PREFIX}"
    GET_CHANNEL_POSTS_AGENT = (
        f"{TELEMETREE_CHANNELS_PREFIX}.{AGENT_PREFIX}.{FETCH_PREFIX}"
    )


"""
TELEGRAPH EVENTS
"""
TELEGRAPH_PREFIX = "telegraph"
TELEGRAPH_PAGE_PREFIX = f"{TELEGRAPH_PREFIX}.pages"


class TelegraphPageTopics(Enum):
    GET_PAGE = f"{TELEGRAPH_PAGE_PREFIX}.{FETCH_PREFIX}"
    CREATE_PAGE = f"{TELEGRAPH_PAGE_PREFIX}.{CREATE_PREFIX}"
    EDIT_PAGE = f"{TELEGRAPH_PAGE_PREFIX}.{UPDATE_PREFIX}"
